package com.example.spa.entity;

public class Statemast {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stateMast.stateCd
     *
     * @mbggenerated
     */
    private String stateCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stateMast.stateName
     *
     * @mbggenerated
     */
    private String stateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stateMast.groupNmae
     *
     * @mbggenerated
     */
    private String groupNmae;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stateMast.stateCd
     *
     * @return the value of stateMast.stateCd
     *
     * @mbggenerated
     */
    public String getStateCd() {
        return stateCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stateMast.stateCd
     *
     * @param stateCd the value for stateMast.stateCd
     *
     * @mbggenerated
     */
    public void setStateCd(String stateCd) {
        this.stateCd = stateCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stateMast.stateName
     *
     * @return the value of stateMast.stateName
     *
     * @mbggenerated
     */
    public String getStateName() {
        return stateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stateMast.stateName
     *
     * @param stateName the value for stateMast.stateName
     *
     * @mbggenerated
     */
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stateMast.groupNmae
     *
     * @return the value of stateMast.groupNmae
     *
     * @mbggenerated
     */
    public String getGroupNmae() {
        return groupNmae;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stateMast.groupNmae
     *
     * @param groupNmae the value for stateMast.groupNmae
     *
     * @mbggenerated
     */
    public void setGroupNmae(String groupNmae) {
        this.groupNmae = groupNmae;
    }
}
